<!--
Шаблон подключается в виде с помощью хелпера echo $this->partial('layout/PartialTemplate', array)
Значения $this->from и $this->subject передаются из хелпера из массива во втором аргументе.
Cм. partial.phtml
-->
<ul>
    <li>From: <?php echo $this->escapeHtml($this->from) ?></li>
    <li>Subject: <?php echo $this->escapeHtml($this->subject) ?></li>
</ul>

<!--
Передача данных была произведена в виде объекта, которому был задан ключ 'keyObject'
-->
<ul>
    <li>From: <?php echo $this->escapeHtml($this->keyObject->from) ?></li>
    <li>Subject: <?php echo $this->escapeHtml($this->keyObject->subject) ?></li>
</ul>


