<?php
/*
 * Хелпер declareVars() позволяет из вида декларировать новые переменные-свойства вида 
 * (создавать новые публичные свойство объекта вида: Zend\View\Renderer\RendererInterface - PhpRenderer)
 * Если новое свойство задекларировано без значения, то ему автоматически присвоится пустая строка "" 
 */
$this->declareVars(
   'varName1',
   'varName2',
    array('varName3' => 'defaultValue',
          'varName4' => array()
    )
);

// Обращение к задекларированным свойствам как к свойствам объекта View
echo $this->varName1;
echo $this->varName3;

////////////////////////////////////////////////////////////////////////////////////////////////////
/*
 * Механизм декларирования свойств:
 * Хелпер вызывает декларируемое свойство объекта Zend\View\Renderer\RendererInterface(PhpRenderer) и передаёт ему значение.
 * Объект RendererInterface с помощью __set($name) и __get($name) перехватывает обращение к декларируемому свойству и 
 * перенаправляет на соответствующий ключ массива PhpRenderer::__vars[$name].
 * 
 * 
 * В объекте вида класса PhpRenderer сохраняются декларируемые переменные в массиве-хранилище:
 * PhpRenderer::__vars['имя деклприруемой переменной'] => <значение деклприруемой переменной>
 * PhpRenderer::__vars - это объект Zend\View\Variables extends ArrayObject.
 */
/*
class DeclareVars extends AbstractHelper {
    
    function __invoke() {
        $view = $this->getView();
        $args = func_get_args();
        foreach ($args as $key) {
            if (is_array($key)) {
                foreach ($key as $name => $value) {
                    $this->declareVar($name, $value);
                }
            } elseif (!isset($view->vars()->$key)) {
                $this->declareVar($key);
            }
        }
    }
    
    protected function declareVar($key, $value = '') {
        // получить объект вида (Zend\View\Renderer\RendererInterface)
        $view = $this->getView();
        // получить у вида объект-массив Zend\View\Variables, в котором хранятся декларируемые переменные
        $vars = $view->vars();
        if (!isset($vars->$key)) {
            // добавить в объект-массив Zend\View\Variables новую переменную
            $vars->$key = $value;
        }
    }
}
*/