<!
    Для каждого Action существует обычно ровно одно представление (шаблон представления), имя которого совпадает с именем Action:
    view/[имя_модуля]/[имя_контроллера]/[имя_action].phtml - view/helloworld/index/index.phtml

    Доступ к переданным данным из Action предоставляется из объекта c помощью:
    $this-[ключ элемента передаваемого массива в new ViewModel(array()) из Action]
!>
<h1>Callback-Factory</h1>
<h2><?php echo $this->greeting; ?></h2>