<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                        => __DIR__ . '/Module.php',
    'Users\Controller\UsersController' => __DIR__ . '/src/Users/Controller/UsersController.php',
    'UsersTest\Framework\TestCase'        => __DIR__ . '/test/Users/Framework/TestCase.php',
    'UsersTest\SampleTest'                => __DIR__ . '/test/Users/SampleTest.php',
);