<?php
// Для лучшего понимания смотреть renderchildmodel.php

// Получить объект класса ViewModel текущего вида с помощью хелпера viewModel()
$currentView = $this->viewModel()->getCurrent();

// отрендерить шаблоны с помощью хелпера renderChildModel($captureTo):
echo $this->renderChildModel('sidebar');
echo $this->renderChildModel('article');

// или через метод хелпера
echo $this->plugin('renderChildModel')->render('article');


